spring:
  application:
    name: lottery-system
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/lottery_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #邮箱验证码服务
  mail:
    host: smtp.qq.com
    username: baxiong11228420@163.com # 你的邮箱
    password: XDhuidDAX6NzpCTR # 刚才拿到的16位授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


logging:
  config: classpath:logback-spring.xml

mybatis:
  #mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-handlers-package: com.bit.lotterysystem.dao.handler