spring:
  application:
    name: lottery-system
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/lottery_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
